// <auto-generated />
namespace MvcOnlineTradeAutomation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig08 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig08));
        
        string IMigrationMetadata.Id
        {
            get { return "202509022207068_mig08"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
